web:
  image: mattermost/mattermost-prod-web
  links:
    - app:app
  environment:
    - MATTERMOST_ENABLE_SSL=false
    - PLATFORM_PORT_80_TCP_PORT=80
  volumes:
      # This directory must have cert files
    - /volumes/web/cert:/cert:ro
    - /etc/localtime:/etc/localtime:ro

app:
  image: mattermost/mattermost-prod-app
  links:
    - db:db
  volumes:
    - /volumes/app/mattermost/config:/mattermost/config:rw
    - /volumes/app/mattermost/data:/mattermost/data:rw
    - /etc/localtime:/etc/localtime:ro

db:
  image: mattermost/mattermost-prod-db
  volumes:
    - /volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
  environment:
    - MM_USERNAME=mmuser
    - MM_PASSWORD=mmuser_password
    - MM_DBNAME=mattermost

lbmm:
  ports:
  - 8443:80
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: rancher/load-balancer-service
  links:
  - web:web
  stdin_open: true
