.catalog:
  name: "Mattermost"
  version: "v1"
  description: "Test mattermost."
  uuid: mattermost

db:
  scale: 1

app:
  scale: 1

web:
  scale: 1

lb-mattermost:
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
